repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        language: system
        files: .*\.go$
        entry: gofmt -s -l -w
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-case-conflict
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
