name: Docker Image CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies and dev image
        id: dependency-cache
        uses: actions/cache@v3
        with:
          path: tmp
          key: deps-${{ runner.os }}-${{ hashFiles('go.mod', '.pre-commit-config.yaml', 'Dockerfile', 'scripts/**') }}
      - name: Build the developer docker image
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: make ci-build
